version: "3.9"

services:
  web:
    image: nginx:stable-alpine
    container_name: schedule_web
    ports:
      - "8005:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx/:rw
    restart: unless-stopped
